// react-calculator/src/components/DigitsContainer/index.jsx
import React, { Component } from 'react';
import DigitBox from '../DigitBox';
import './index.css';

export default class DigitsContainer extends Component {
    constructor(props) {
        super(props);
        this.state = {
            display: ''
        };
    }

    reset = () => {
        this.setState({ display: '' });
    };

    backspace = () => {
        this.setState({
            display: this.state.display.slice(0, -1)
        });
    };

    calculate = () => {
        this.setState({
            display: (eval(this.state.display) || '') + ''
        });
    };

    onClick = button => {
        if (button === '=') {
            this.calculate();
        } else if (button === 'C') {
            this.reset();
        } else if (button === 'CE') {
            this.backspace();
        } else {
            this.setState({
                display: this.state.display + button
            });
        }
    };

    render() {
        return (
            <div className="calculator">
                <div className="display-container">
                    <h2 className="display-text">{this.state.display}</h2>
                </div>
                <div className="secondary-row-container">
                    <div className="digits-container">
                        <div className="digits-row">
                            <DigitBox styledBox="operator" digitNumber={'C'} onSelectDigit={this.onClick} />
                            <DigitBox styledBox="operator" digitNumber={'CE'} onSelectDigit={this.onClick} />
                            <DigitBox styledBox="operator" digitNumber={'/'} onSelectDigit={this.onClick} />
                        </div>
                        <div className="digits-row">
                            <DigitBox digitNumber={7} onSelectDigit={this.onClick} />
                            <DigitBox digitNumber={8} onSelectDigit={this.onClick} />
                            <DigitBox digitNumber={9} onSelectDigit={this.onClick} />
                        </div>
                        <div className="digits-row">
                            <DigitBox digitNumber={4} onSelectDigit={this.onClick} />
                            <DigitBox digitNumber={5} onSelectDigit={this.onClick} />
                            <DigitBox digitNumber={6} onSelectDigit={this.onClick} />
                        </div>
                        <div className="digits-row">
                            <DigitBox digitNumber={1} onSelectDigit={this.onClick} />
                            <DigitBox digitNumber={2} onSelectDigit={this.onClick} />
                            <DigitBox digitNumber={3} onSelectDigit={this.onClick} />
                        </div>
                        <div className="digits-row">
                            <DigitBox
                                styledBox="stretched"
                                digitNumber={0}
                                onSelectDigit={this.onClick}
                            />
                            <DigitBox digitNumber={'.'} onSelectDigit={this.onClick} />
                        </div>
                    </div>
                    <div className="operations-container">
                        <DigitBox styledBox="operator" digitNumber={'*'} onSelectDigit={this.onClick} />
                        <DigitBox styledBox="operator" digitNumber={'+'} onSelectDigit={this.onClick} />
                        <DigitBox styledBox="operator" digitNumber={'-'} onSelectDigit={this.onClick} />
                        <DigitBox
                            styledBox="stretched operator"
                            digitNumber={'='}
                            onSelectDigit={this.onClick}
                        />
                    </div>
                </div>
            </div>
        );
    }
}

// vue-calculator/src/components/DigitsContainer.vue
<template>
  <div class="calculator">
    <div class="display-container">
      <h2 class="display-text">{{display}}</h2>
    </div>
    <div class="secondary-row-container">
      <div class="digits-container">
        <div class="digits-row">
          <DigitBox styledBox="operator" digitNumber="C" @onSelectDigit="onClick"/>
          <DigitBox styledBox="operator" digitNumber="CE" @onSelectDigit="onClick"/>
          <DigitBox styledBox="operator" digitNumber="/" @onSelectDigit="onClick"/>
        </div>
        <div class="digits-row">
          <DigitBox digitNumber="7" @onSelectDigit="onClick"/>
          <DigitBox digitNumber="8" @onSelectDigit="onClick"/>
          <DigitBox digitNumber="9" @onSelectDigit="onClick"/>
        </div>
        <div class="digits-row">
          <DigitBox digitNumber="4" @onSelectDigit="onClick"/>
          <DigitBox digitNumber="5" @onSelectDigit="onClick"/>
          <DigitBox digitNumber="6" @onSelectDigit="onClick"/>
        </div>
        <div class="digits-row">
          <DigitBox digitNumber="1" @onSelectDigit="onClick"/>
          <DigitBox digitNumber="2" @onSelectDigit="onClick"/>
          <DigitBox digitNumber="3" @onSelectDigit="onClick"/>
        </div>
        <div class="digits-row">
          <DigitBox class="stretched" digitNumber="0" @onSelectDigit="onClick"/>
          <DigitBox digitNumber="." @onSelectDigit="onClick"/>
        </div>
      </div>
      <div class="operations-container">
        <DigitBox styledBox="operator" digitNumber="*" @onSelectDigit="onClick"/>
        <DigitBox styledBox="operator" digitNumber="+" @onSelectDigit="onClick"/>
        <DigitBox styledBox="operator" digitNumber="-" @onSelectDigit="onClick"/>
        <DigitBox styledBox="stretched operator" digitNumber="=" @onSelectDigit="onClick"/>
      </div>
    </div>
  </div>
</template>

<script>
  import DigitBox from './DigitBox';

  export default {
    components: { DigitBox },
    data() {
      return {
        display: ''
      }
    },
    methods: {
      backspace() {
        this.display = this.display.slice(0, -1);
      },
      calculate() {
        this.display = eval(this.display || '') + ''
      },
      reset() {
        this.display = '';
      },
      onClick(button) {
        switch (button) {
          case '=':
            this.calculate();
            break;
          case 'C':
            this.reset();
            break;
          case 'CE':
            this.backspace();
            break;
          default:
            this.display += button;
        }
      }
    }
  };
</script>

<style scoped>
  .digits-container {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .digits-row {
    display: flex;
    flex-direction: row;
    width: 100%;
  }

  .display-container {
    background-color: darkgrey;
    height: 100px;
  }

  .calculator {
    text-align: center;
    display: flex;
    flex-direction: column;
    width: 416px;
    justify-content: center;
  }

  .display-text {
    color: black;
  }

  .secondary-row-container {
    display: flex;
    flex-direction: row;
  }

  .operations-container {
    display: flex;
    flex-direction: column;
  }

  .stretched {
    flex-grow: 2;
  }
</style>
